from __future__ import annotations

from solutions._08_resonant_collinearity import Map

input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""


def test_08_find_antinodes():
    map = Map(input)
    map.find_antinodes()
    assert map.count_antinodes() == 14


def test_08_find_antinodes_with_resonant_harmonics():
    map = Map(input)
    map.find_antinodes_with_resonant_harmonics()
    assert map.count_antinodes() == 34
